// ============================================================================
// Morpheus models in grok's `/model` picker.
//
// The app publishes every model it can currently serve — the local ones and any
// with a LIVE session — as grok model entries pointing at the loopback
// OpenAI-compatible endpoint. Pick one with `/model` and grok talks to Morpheus.
//
// WHY THIS INSTEAD OF INTERCEPTING A COMMAND
// Opening a session from the terminal needs a keystroke to reach our code, and
// the only seam for that is grok's internal leader socket — an undocumented
// protocol belonging to a tool that updates itself. USING a session needs none
// of that: it is a provider entry in a documented config file. Same value for
// the part that matters, none of the fragility. Sessions are opened in the app.
//
// WHERE IT IS WRITTEN, AND WHY THAT FILE
// `$GROK_HOME/managed_config.toml`. grok's merge order is:
//   1. /etc/grok/managed_config.toml
//   2. $GROK_HOME/managed_config.toml   <- us
//   3. $GROK_HOME/config.toml           <- the user, and it WINS over us
// so we can add models without being able to override a single one of their
// settings, and their file is never read, parsed or rewritten. The policy
// machinery that also lives in this layer (fail-closed, staleness) is keyed on
// `requirements.toml` and a sync marker, neither of which we touch — verified
// in xai-grok-config/src/managed_cache.rs before choosing this file.
// ============================================================================

import { chmodSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';

export const managedConfigPath = (): string =>
  path.join(homedir(), '.grok', 'managed_config.toml');

export type GrokModelInput = {
  /** The id `/v1/models` advertises — what grok must send back as `model`. */
  id: string;
  /** Human label, e.g. "deepseek-v4 (session)". */
  label: string;
};

export type GrokModelsConfigInput = {
  baseUrl: string;
  apiKey: string;
  models: GrokModelInput[];
};

/**
 * Escape a value for a TOML basic string.
 *
 * Model ids and names are CHAIN DATA — anyone can register a model called
 * `evil"\n[model.x]`. They land in a config file that grok parses, so a bare
 * interpolation is a config-injection hole. Quotes and backslashes are escaped;
 * control characters are refused outright rather than encoded, because no
 * legitimate model name contains one and refusing is the safer failure.
 */
export function tomlString(value: string): string {
  if (/[\u0000-\u001f\u007f]/.test(value)) {
    throw new Error('refusing to write a TOML value containing a control character');
  }
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * A grok config key for a model.
 *
 * Prefixed so these are obviously ours in the `/model` list and can never
 * collide with a model the user configured themselves. Anything outside the
 * safe set is replaced rather than quoted: a bare key keeps the picker readable.
 */
export function grokModelKey(id: string): string {
  // NO DOTS. A dot is TOML's table separator, so `[model.morpheus-qwen2.5-1.5b]`
  // parses as the nested tables morpheus-qwen2 -> 5-1 -> 5b, not as one key —
  // grok then looked up "morpheus-qwen2", found nothing, and fell through to
  // xAI's own API with "the model morpheus-qwen2 does not exist". Quoting the
  // key would also work, but a bare key cannot be mis-parsed by anything.
  const safe = id.replace(/[^A-Za-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
  return `morpheus-${safe || 'model'}`;
}

/**
 * The whole managed config file.
 *
 * Deliberately does NOT set `[models] default` or any other global: this file
 * only ever ADDS `[model.*]` entries. Setting a default here would change which
 * model grok uses for unrelated work, which is not ours to decide.
 *
 * `api_key` is written directly on each model rather than via `model_provider`:
 * grok treats a loopback URL as non-first-party and installs a fail-closed auth
 * provider for provider-referencing models, which would break every request.
 */
export function buildGrokModelsToml(input: GrokModelsConfigInput): string {
  const lines: string[] = [
    '# Generated by the Morpheus desktop app. Do not edit — it is rewritten',
    '# whenever your sessions change.',
    '#',
    '# This file is layered BELOW your own config.toml, so nothing here can',
    '# override a setting you made. It only adds Morpheus models.',
    '',
  ];

  if (!input.models.length) {
    lines.push('# No Morpheus model is currently servable — open a session in the app.');
    lines.push('');
    return lines.join('\n');
  }

  const used = new Set<string>();
  for (const model of input.models) {
    // Ids differing only in punctuation ("a.b" and "a-b") now reduce to the
    // same key, and a duplicate table is a TOML parse error that would take the
    // whole file down — not just one model.
    let key = grokModelKey(model.id);
    if (used.has(key)) {
      let n = 2;
      while (used.has(`${key}-${n}`)) n++;
      key = `${key}-${n}`;
    }
    used.add(key);
    lines.push(`[model.${key}]`);
    // `model` is what grok sends as the request's model field, so it must be
    // the id the endpoint advertises — not the display label, and not our key.
    lines.push(`model = ${tomlString(model.id)}`);
    lines.push(`name = ${tomlString(`Morpheus: ${model.label}`)}`);
    lines.push(`base_url = ${tomlString(input.baseUrl)}`);
    lines.push(`api_key = ${tomlString(input.apiKey)}`);
    // The credential that actually gets through. grok treats a loopback URL as
    // first-party xAI and, with its disable_api_key_auth kill switch on, swaps
    // `api_key` for its own IdP session token before the request leaves — so
    // the endpoint saw an 838-char JWT instead of our key and refused it. This
    // header it does not rewrite.
    lines.push(
      `extra_headers = { "X-Morpheus-Key" = ${tomlString(input.apiKey)} }`,
    );
    lines.push('api_backend = "chat_completions"');
    lines.push('');
  }
  return lines.join('\n');
}

/** Write it 0600 — it carries the endpoint's bearer token. */
export function writeGrokModelsConfig(filePath: string, contents: string): void {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, contents, { encoding: 'utf8', mode: 0o600 });
  // `mode` applies only on creation; an existing file keeps its old bits, which
  // would leave the token readable if the file predates this.
  chmodSync(filePath, 0o600);
}

/**
 * The shell line that opens grok on a given Morpheus model.
 *
 * `-m` takes the CONFIG KEY, not the model id, because that is what grok
 * resolves against its model map — the same key `buildGrokModelsToml` writes.
 * Control characters are refused rather than quoted: model names come from the
 * chain, and a newline would produce a `.command` file spanning lines that
 * cannot be reviewed by eye.
 */
export function buildGrokLaunchScript(input: {
  grokPath: string;
  modelId: string;
  cwd: string;
}): string {
  for (const [field, value] of Object.entries(input)) {
    if (/[\u0000-\u001f\u007f]/.test(String(value))) {
      throw new Error(`Refusing to build a launch command: ${field} contains a control character.`);
    }
  }
  const q = (v: string): string => `'${String(v).replace(/'/g, `'\\''`)}'`;
  return [
    '#!/bin/bash',
    `cd ${q(input.cwd)} || exit 1`,
    `exec ${q(input.grokPath)} -m ${q(grokModelKey(input.modelId))}`,
    '',
  ].join('\n');
}

/**
 * What to publish to grok, out of what the endpoint advertises.
 *
 * This used to keep its own STICKY set, growing forever, because grok reads its
 * config once at startup: a list that tracked live sessions exactly changed
 * every time one opened, and the user had to restart grok to see it. That
 * workaround is gone, and the stability now comes from the endpoint itself —
 * it advertises the user's STARRED models whether or not a session is open, so
 * this list only changes when the user changes what they starred. One place
 * decides what exists; this function only decides what grok is told about.
 *
 * Local models are DROPPED. grok is a coding agent: it always sends tools and
 * stream together, and the local runtime answers that with "Cannot use tools
 * with stream" every time — so listing one offers a guaranteed failure, dressed
 * up as a choice.
 */
export function selectGrokModels(
  advertised: readonly { id: string; label: string; isLocal?: boolean }[],
): GrokModelInput[] {
  const byId = new Map<string, GrokModelInput>();
  for (const m of advertised) {
    if (!m?.id || m.isLocal) continue;
    byId.set(m.id, { id: m.id, label: m.label || m.id });
  }
  return [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));
}
