// ============================================================================
// The `/start` command, as an opencode TUI plugin.
//
// Shipped as a STRING rather than a file in the build tree on purpose: the app
// writes it at runtime, so there is no packaged asset to resolve, no path that
// differs between `npm run dev` and a signed .app, and nothing to keep in sync
// with electron-vite's bundling.
//
// WHERE IT IS INSTALLED, AND WHY THAT CHANGED
// Into `~/.config/opencode/plugins/`, which opencode auto-loads at startup for
// every session. It used to be declared in the app's OWN config as a
// `["<path>", {baseUrl, apiKey}]` tuple, which meant `/start` existed only in
// terminals the app had launched — so a user who ran `opencode` themselves saw
// no /start at all, which is precisely what installing the app should have set
// up. The auto-load directory is also the only route that does NOT touch the
// user's `~/.config/opencode/opencode.jsonc`: it is JSONC, and a round-trip
// through JSON.parse/stringify would silently delete their comments.
//
// Directory-loaded plugins receive NO options, so the endpoint URL and token
// cannot arrive that way. Both files read a DESCRIPTOR the app writes (0600)
// whose absolute path is baked in here at write time. A path is not a secret,
// so these files still carry no credential, and rotating the token rewrites
// only the descriptor.
//
// WHAT IT DOES
//   /start  → pick a model (searchable) → pick a provider (searchable, priced)
//           → pick a duration (searchable) → see the real stake → confirm
//           → the app opens the session.
//
// WHERE THE SECURITY ACTUALLY IS
// The confirmation dialog is a real boundary against an AGENT — a model cannot
// press a key — but it is client-side, and anything holding the token could
// POST /morpheus/v1/sessions directly. So the dialog is UX plus agent
// resistance; the enforcement is in the app: `allowAutoOpen` off by default,
// per-session and per-day MOR caps, a per-day session count, and a stake
// re-priced at spend time so a caller cannot name its own number. This file is
// deliberately incapable of raising any of those.
//
// API NOTES, verified against @opencode-ai/plugin@1.18.10 (the installed
// opencode is 1.18.10) rather than from documentation:
//   - `TuiPluginModule` is `{ id?, tui }`, and `TuiPlugin` is
//     `(api, options, meta) => Promise<void>`.
//   - `api.command.register(() => TuiCommand[])` is how a plugin adds a slash
//     command. It is marked @deprecated in favour of
//     `api.keymap.registerLayer({ commands, bindings })`, and it is OPTIONAL on
//     the api object — hence the guard below. The replacement needs the
//     `@opentui/keymap` Command shape, which is not part of the plugin
//     package's public types, so the legacy call is what can be written
//     correctly today. Migrate when v2 lands.
//   - `api.ui.DialogSelect` / `DialogConfirm` are Solid components. They are
//     CALLED AS FUNCTIONS here rather than through JSX so that this file needs
//     no JSX transform and can ship as plain JS.
//   - `Hooks.config` is a SERVER hook, and `PluginModule`/`TuiPluginModule`
//     make `server` and `tui` mutually exclusive (`tui?: never` / `server?:
//     never`), so the provider registration lives in a second file.
// ============================================================================

const FS_IMPORT = ['import', '{ readFileSync }', 'from', "'node:fs';"].join(' ');

/**
 * The `/start` plugin source, with the descriptor path baked in.
 *
 * `descriptorPath` is embedded as a JSON string literal so a path containing
 * quotes or backslashes cannot break out of it.
 */
export const buildStartPlugin = (descriptorPath: string): string =>
  MORPHEUS_START_PLUGIN.replace(
    '__MORPHEUS_DESCRIPTOR__',
    JSON.stringify(descriptorPath).slice(1, -1),
  ).replace('__FS_IMPORT__', FS_IMPORT);

const MORPHEUS_START_PLUGIN = String.raw`
// Generated by the Morpheus desktop app. Do not edit — it is rewritten on every
// launch. The command it adds is /start.

const PRESETS = [
  { label: '5 minutes (the chain minimum)', seconds: 305 },
  { label: '30 minutes', seconds: 1800 },
  { label: '1 hour', seconds: 3600 },
  { label: '6 hours', seconds: 21600 },
  { label: '12 hours', seconds: 43200 },
  { label: '1 day', seconds: 86400 },
  { label: '3 days', seconds: 259200 },
  { label: '7 days', seconds: 604800 },
];

const mor = (n) =>
  typeof n === 'number' && isFinite(n)
    ? (n < 1 ? n.toFixed(4) : n.toFixed(2)) + ' MOR'
    : '—';

const humanDuration = (sec) => {
  const preset = PRESETS.find((p) => p.seconds === sec);
  if (preset) return preset.label;
  if (sec % 86400 === 0) return (sec / 86400) + ' days';
  if (sec % 3600 === 0) return (sec / 3600) + ' hours';
  if (sec % 60 === 0) return (sec / 60) + ' minutes';
  return sec + ' seconds';
};

__FS_IMPORT__

const DESCRIPTOR = "__MORPHEUS_DESCRIPTOR__";

// Read on every call, not once at load: the app rewrites this when the port
// changes or the key is regenerated, and a plugin holding a stale copy would
// fail with a 401 the user cannot explain.
const endpoint = () => {
  try {
    const d = JSON.parse(readFileSync(DESCRIPTOR, 'utf8'));
    return {
      baseUrl: String(d.baseUrl || '').replace(/\/$/, ''),
      apiKey: String(d.apiKey || ''),
    };
  } catch {
    return { baseUrl: '', apiKey: '' };
  }
};

export const tui = async (api) => {

  const toast = (message, variant) =>
    api.ui.toast({ message: message, variant: variant || 'info' });

  // Every call is loopback-only and carries the app's bearer token. A non-2xx
  // response carries a message written for a human; surface it verbatim rather
  // than inventing one, because the app's refusals name the exact cap that
  // fired and what to do about it.
  const call = async (path, init) => {
    const { baseUrl, apiKey } = endpoint();
    if (!baseUrl || !apiKey) {
      throw new Error(
        'Could not read the Morpheus endpoint details. Is the Morpheus app running with its OpenAI-compatible API enabled?',
      );
    }
    const res = await fetch(baseUrl + path, {
      ...(init || {}),
      headers: {
        Authorization: 'Bearer ' + apiKey,
        'content-type': 'application/json',
        ...((init && init.headers) || {}),
      },
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) {
      const detail =
        (body && body.error && body.error.message) ||
        ('The endpoint returned ' + res.status + '.');
      throw new Error(detail);
    }
    return body;
  };

  const dialog = api.ui.dialog;

  // ---- step 4: confirm, then spend --------------------------------------
  const confirmAndOpen = (model, provider, durationSec, quote) => {
    const lines = [
      'Model:     ' + model.name,
      'Provider:  ' + provider.provider,
      'Duration:  ' + humanDuration(durationSec),
      '',
      'Stake:     ' + mor(quote.stakeMor),
      '',
      'The stake is collateral, not a fee. It is locked until the end of',
      'the day the session closes, then returns automatically.',
    ].join('\n');

    dialog.replace(() =>
      api.ui.DialogConfirm({
        title: 'Open this Morpheus session?',
        message: lines,
        onCancel: () => dialog.clear(),
        onConfirm: () => {
          dialog.clear();
          toast('Opening the session on-chain…');
          call('/morpheus/v1/sessions', {
            method: 'POST',
            body: JSON.stringify({
              modelId: model.id,
              bidId: provider.bidId,
              durationSec: durationSec,
              confirm: true,
              // The figure shown on the screen the user just approved. The app
              // treats it as a CEILING and refuses if its own re-price comes
              // out higher, so what was confirmed is what can be staked.
              confirmedStakeMor: quote.stakeMor,
            }),
          }).then(
            (opened) => {
              toast(
                'Session open — staked ' +
                  mor(opened.stakeMor) +
                  '. Pick "morpheus/' +
                  opened.model +
                  '" to use it.',
                'success',
              );
              // opencode 1.18.10 exposes no way for a plugin to SET the active
              // model, only to open the picker. Opening it puts the freshly
              // served model one keystroke away instead of leaving the user to
              // remember the name.
              if (api.client && api.client.tui && api.client.tui.openModels) {
                api.client.tui.openModels().catch(() => {});
              }
            },
            (e) => toast('Could not open the session: ' + e.message, 'error'),
          );
        },
      }),
    );
  };

  // ---- step 3: duration --------------------------------------------------
  const pickDuration = (model, provider, limits) => {
    const capSec = limits.maxSessionSeconds || 604800;
    const minSec = limits.minSessionSeconds || 305;
    const choices = PRESETS.filter(
      (p) => p.seconds <= capSec && p.seconds >= minSec,
    ).map((p) => ({
      title: p.label,
      value: p.seconds,
      // Priced from the provider's own per-hour figure, so the list is
      // scannable before any round trip. The CONFIRM screen shows the real
      // quote from the app, which is the number that binds.
      description:
        '≈ ' + mor((provider.stakeMorPerHour * p.seconds) / 3600) + ' to stake',
    }));

    dialog.replace(() =>
      api.ui.DialogSelect({
        title: 'How long? (' + model.name + ')',
        placeholder: 'Filter durations…',
        options: choices,
        onSelect: (option) => {
          toast('Pricing ' + humanDuration(option.value) + '…');
          call('/morpheus/v1/quote', {
            method: 'POST',
            body: JSON.stringify({
              modelId: model.id,
              bidId: provider.bidId,
              durationSec: option.value,
            }),
          }).then(
            (quote) => {
              if (!quote.allowed) {
                dialog.clear();
                toast(quote.reason || 'That session is not allowed.', 'warning');
                return;
              }
              confirmAndOpen(model, provider, option.value, quote);
            },
            (e) => {
              dialog.clear();
              toast('Could not price that session: ' + e.message, 'error');
            },
          );
        },
      }),
    );
  };

  // ---- step 2: provider --------------------------------------------------
  const pickProvider = (model, limits) => {
    const sorted = [...model.providers].sort(
      (a, b) => a.stakeMorPerHour - b.stakeMorPerHour,
    );
    // Label by PRICE, not by position. Tying "cheapest" to index 0 makes the
    // label a restatement of the sort rather than a fact about the provider —
    // so a broken sort would relabel the dearest option "cheapest" and the
    // badge would agree with it.
    const best = Math.min.apply(null, sorted.map((p) => p.stakeMorPerHour));
    dialog.replace(() =>
      api.ui.DialogSelect({
        title: 'Which provider? (' + model.name + ')',
        placeholder: 'Filter providers…',
        options: sorted.map((p) => ({
          title: p.provider,
          value: p,
          description:
            mor(p.stakeMorPerHour) +
            ' / hour' +
            (p.stakeMorPerHour === best ? '  · cheapest' : ''),
        })),
        onSelect: (option) => pickDuration(model, option.value, limits),
      }),
    );
  };

  // ---- step 1: model -----------------------------------------------------
  const start = async () => {
    let status;
    try {
      status = await call('/morpheus/v1/status');
    } catch (e) {
      toast('Cannot reach the Morpheus app: ' + e.message, 'error');
      return;
    }
    if (!status.canOpen) {
      // Say WHY, and where the switch is. A bare "not allowed" sends the user
      // hunting through an app they may not have open.
      toast(status.reason || 'Opening sessions from here is turned off.', 'warning');
      return;
    }

    toast('Loading the Morpheus model catalog…');
    let catalog;
    try {
      catalog = await call('/morpheus/v1/catalog');
    } catch (e) {
      toast('Could not load the catalog: ' + e.message, 'error');
      return;
    }
    const models = (catalog.models || []).filter(
      (m) => m.providers && m.providers.length,
    );
    if (!models.length) {
      toast('No Morpheus model currently has a live provider bid.', 'warning');
      return;
    }

    const limits = {
      maxSessionSeconds: catalog.maxSessionSeconds,
      minSessionSeconds: catalog.minSessionSeconds,
    };
    const cheapest = (m) =>
      Math.min.apply(null, m.providers.map((p) => p.stakeMorPerHour));

    dialog.replace(() =>
      api.ui.DialogSelect({
        title: 'Start a Morpheus session — pick a model',
        placeholder: 'Search models…',
        options: models
          .slice()
          .sort((a, b) => a.name.localeCompare(b.name))
          .map((m) => ({
            title: m.name,
            value: m,
            description:
              m.providers.length +
              (m.providers.length === 1 ? ' provider' : ' providers') +
              '  · from ' +
              mor(cheapest(m)) +
              ' / hour',
          })),
        onSelect: (option) => pickProvider(option.value, limits),
      }),
    );
  };

  const commands = () => [
    {
      title: 'Start a Morpheus session',
      value: 'morpheus.start',
      description: 'Pick a model, provider and duration, then stake MOR',
      category: 'Morpheus',
      slash: { name: 'start', aliases: ['morpheus'] },
      onSelect: () => {
        start().catch((e) => toast('/start failed: ' + e.message, 'error'));
      },
    },
  ];

  if (api.command && typeof api.command.register === 'function') {
    const dispose = api.command.register(commands);
    api.lifecycle.onDispose(() => dispose && dispose());
    return;
  }

  // Fail LOUDLY. Silently registering nothing would look like the app is
  // broken, with no clue that the host dropped the API this depends on.
  toast(
    'This opencode build no longer exposes the plugin command API, so /start could not be registered. Update the Morpheus app.',
    'error',
  );
};
`;

/**
 * The companion SERVER plugin: registers the Morpheus provider.
 *
 * `/start` is useless on its own if opencode has never heard of the provider —
 * the session opens and the model cannot be selected. When the app launches
 * opencode it supplies a config with the provider block, but a terminal the
 * user opened themselves has no such config, which is the case this exists for.
 *
 * `Hooks.config` receives the resolved config and mutates it in place. It only
 * ADDS `provider.morpheus`; anything the user has configured is left alone, and
 * their `opencode.jsonc` is never read or rewritten.
 */
export const buildProviderPlugin = (descriptorPath: string): string =>
  MORPHEUS_PROVIDER_PLUGIN.replace(
    '__MORPHEUS_DESCRIPTOR__',
    JSON.stringify(descriptorPath).slice(1, -1),
  ).replace('__FS_IMPORT__', FS_IMPORT);

const MORPHEUS_PROVIDER_PLUGIN = String.raw`
// Generated by the Morpheus desktop app. Do not edit — it is rewritten on every
// launch. It registers the Morpheus provider so /start's sessions are usable.

__FS_IMPORT__

const DESCRIPTOR = "__MORPHEUS_DESCRIPTOR__";

export const server = async () => ({
  config: async (config) => {
    let d;
    try {
      d = JSON.parse(readFileSync(DESCRIPTOR, 'utf8'));
    } catch {
      // The app is not running, or has not written its endpoint yet. Adding a
      // provider pointed at nothing would put dead models in the picker, so do
      // nothing at all.
      return;
    }
    if (!d || !d.baseUrl || !d.apiKey) {
      return;
    }

    const models = {};
    for (const m of d.models || []) {
      models[m.id] = { name: m.label || m.id };
    }

    config.provider = config.provider || {};
    // Only ever ADD our own key. Merging into whatever else is here would be
    // editing the user's configuration, which this integration does not do.
    config.provider.morpheus = {
      npm: '@ai-sdk/openai-compatible',
      name: 'Morpheus',
      options: { baseURL: d.baseUrl, apiKey: d.apiKey },
      models,
    };
  },
});
`;
