// ============================================================================
// The `/start` command, as an opencode TUI plugin.
//
// Shipped as a STRING rather than a file in the build tree on purpose: the app
// writes it at runtime, so there is no packaged asset to resolve, no path that
// differs between `npm run dev` and a signed .app, and nothing to keep in sync
// with electron-vite's bundling.
//
// WHERE IT IS INSTALLED, AND WHY THAT CHANGED
// Into `~/.config/opencode/plugins/`, which opencode auto-loads at startup for
// every session. It used to be declared in the app's OWN config as a
// `["<path>", {baseUrl, apiKey}]` tuple, which meant `/start` existed only in
// terminals the app had launched — so a user who ran `opencode` themselves saw
// no /start at all, which is precisely what installing the app should have set
// up. The auto-load directory is also the only route that does NOT touch the
// user's `~/.config/opencode/opencode.jsonc`: it is JSONC, and a round-trip
// through JSON.parse/stringify would silently delete their comments.
//
// Directory-loaded plugins receive NO options, so the endpoint URL and token
// cannot arrive that way. Both files read a DESCRIPTOR the app writes (0600)
// whose absolute path is baked in here at write time. A path is not a secret,
// so these files still carry no credential, and rotating the token rewrites
// only the descriptor.
//
// WHAT IT DOES
//   /start  → pick a model (searchable) → pick a provider (searchable, priced)
//           → pick a duration (searchable) → see the real stake → confirm
//           → the app opens the session.
//
// WHERE THE SECURITY ACTUALLY IS
// The confirmation dialog is a real boundary against an AGENT — a model cannot
// press a key — but it is client-side, and anything holding the token could
// POST /morpheus/v1/sessions directly. So the dialog is UX plus agent
// resistance; the enforcement is in the app: `allowAutoOpen` off by default,
// per-session and per-day MOR caps, a per-day session count, and a stake
// re-priced at spend time so a caller cannot name its own number. This file is
// deliberately incapable of raising any of those.
//
// API NOTES, verified against @opencode-ai/plugin@1.18.10 (the installed
// opencode is 1.18.10) rather than from documentation:
//   - `TuiPluginModule` is `{ id?, tui }`, and `TuiPlugin` is
//     `(api, options, meta) => Promise<void>`.
//   - `api.command.register(() => TuiCommand[])` is how a plugin adds a slash
//     command. It is marked @deprecated in favour of
//     `api.keymap.registerLayer({ commands, bindings })`, and it is OPTIONAL on
//     the api object — hence the guard below. The replacement needs the
//     `@opentui/keymap` Command shape, which is not part of the plugin
//     package's public types, so the legacy call is what can be written
//     correctly today. Migrate when v2 lands.
//   - `api.ui.DialogSelect` / `DialogConfirm` are Solid components. They are
//     CALLED AS FUNCTIONS here rather than through JSX so that this file needs
//     no JSX transform and can ship as plain JS.
//   - `Hooks.config` is a SERVER hook, and `PluginModule`/`TuiPluginModule`
//     make `server` and `tui` mutually exclusive (`tui?: never` / `server?:
//     never`), so the provider registration lives in a second file.
// ============================================================================

const FS_IMPORT = ['import', '{ readFileSync }', 'from', "'node:fs';"].join(' ');

/**
 * The `/start` plugin source, with the descriptor path baked in.
 *
 * `descriptorPath` is embedded as a JSON string literal so a path containing
 * quotes or backslashes cannot break out of it.
 */
/**
 * The companion SERVER plugin: registers the Morpheus provider.
 *
 * `/start` is useless on its own if opencode has never heard of the provider —
 * the session opens and the model cannot be selected. When the app launches
 * opencode it supplies a config with the provider block, but a terminal the
 * user opened themselves has no such config, which is the case this exists for.
 *
 * `Hooks.config` receives the resolved config and mutates it in place. It only
 * ADDS `provider.morpheus`; anything the user has configured is left alone, and
 * their `opencode.jsonc` is never read or rewritten.
 */
export const buildProviderPlugin = (descriptorPath: string): string =>
  MORPHEUS_PROVIDER_PLUGIN.replace(
    '__MORPHEUS_DESCRIPTOR__',
    JSON.stringify(descriptorPath).slice(1, -1),
  ).replace('__FS_IMPORT__', FS_IMPORT);

const MORPHEUS_PROVIDER_PLUGIN = String.raw`
// Generated by the Morpheus desktop app. Do not edit — it is rewritten on every
// launch. It registers the Morpheus provider so /start's sessions are usable.

__FS_IMPORT__

const DESCRIPTOR = "__MORPHEUS_DESCRIPTOR__";

export const server = async () => ({
  config: async (config) => {
    let d;
    try {
      d = JSON.parse(readFileSync(DESCRIPTOR, 'utf8'));
    } catch {
      // The app is not running, or has not written its endpoint yet. Adding a
      // provider pointed at nothing would put dead models in the picker, so do
      // nothing at all.
      return;
    }
    if (!d || !d.baseUrl || !d.apiKey) {
      return;
    }

    const models = {};
    for (const m of d.models || []) {
      models[m.id] = { name: m.label || m.id };
    }

    config.provider = config.provider || {};
    // Only ever ADD our own key. Merging into whatever else is here would be
    // editing the user's configuration, which this integration does not do.
    //
    // d.baseUrl is the bare ORIGIN (http://127.0.0.1:<port>, no /v1) — the
    // descriptor's one field shared with the /start command plugin, which
    // needs the origin to build /morpheus/v1/* paths itself. @ai-sdk/
    // openai-compatible's baseURL is a different contract: it appends
    // /chat/completions directly onto whatever is given, so it needs /v1
    // appended HERE, at the one consumer that wants it, not by changing what
    // the descriptor means for everyone who reads it. Passing the bare
    // origin through unchanged was a real bug: opencode posted to
    // /chat/completions instead of /v1/chat/completions and the endpoint
    // rejected it outright.
    config.provider.morpheus = {
      npm: '@ai-sdk/openai-compatible',
      name: 'Morpheus',
      options: { baseURL: d.baseUrl.replace(/\/+$/, '') + '/v1', apiKey: d.apiKey },
      models,
    };
  },
});
`;
